ProjectFindStar/Areas/Admin/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProjectFindStar.Areas.Admin.Models;
using ProjectFindStar.Areas.Admin.Services;
using ProjectFindStar.Data;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace ProjectFindStar.Areas.Admin.Controllers
{
    [Area(nameof(Admin))]
    [Authorize]
    public class UsersController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly UserManager<AppUser> userManager;
        private readonly UsersService service;

        public UsersController(ApplicationDbContext context, UserManager<AppUser> userManager)
        {
            this.context = context;
            this.userManager = userManager;
            this.service = new UsersService(userManager);
        }

        public async Task<IActionResult> Index()
        {
        
            this.ViewData["ActivePage"] = "users";
            List<UserViewModel> users = await service.ParseUsersAsync(this.context.Users);
            return this.View(users);
        }

        public async Task<IActionResult> Delete(string id)
        {
            AppUser user = await this.userManager.FindByIdAsync(id);
            await this.userManager.UpdateSecurityStampAsync(user);
            if (user == await this.userManager.GetUserAsync(HttpContext.User))
            {
                foreach (var cookie in Request.Cookies.Keys)
                {
                    Response.Cookies.Delete(cookie);
                }
            }
            await this.userManager.DeleteAsync(user);
            return this.Redirect("/Admin/Users");
        }
    }
}

ProjectFindStar/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="~/admin/img/apple-icon.png">
    <link rel="icon" type="image/png" href="~/admin/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
        Dashboard
    </title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <!-- CSS Files -->
    <link href="~/admin/css/material-dashboard.css?v=2.1.0" rel="stylesheet" />
</head>
<body class="">
    <div class="wrapper ">
        <div class="sidebar" data-color="orange" data-background-color="white">
            <div class="logo">
                <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="simple-text logo-normal">
                    FindStar Inc.
                </a>
            </div>
            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li id="index" class="nav-item">
                        <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="nav-link">
                            <i class="material-icons">dashboard</i>
                            <p>Dashboard</p>
                        </a>
                    </li>
                    <li id="users" class="nav-item">
                        <a asp-area="Admin" asp-controller="Users" asp-action="Index" class="nav-link">
                            <i class="material-icons">face</i>
                            <p>List Users</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
                <div class="container-fluid">
                    <div class="navbar-wrapper">
                        <a class="navbar-brand" href="#pablo">Dashboard</a>
                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="navbar-toggler-icon icon-bar"></span>
                        <span class="navbar-toggler-icon icon-bar"></span>
                        <span class="navbar-toggler-icon icon-bar"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="#pablo">
                                    <i class="material-icons">notifications</i> Notifications
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">
                                    <i class="material-icons">home</i> Return to Home
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- End Navbar -->
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    &copy; 2018 - FindStar
                </div>
            </footer>
        </div>
    </div>
    <!--   Core JS Files   -->
    <script src="~/admin/js/core/jquery.min.js" type="text/javascript"></script>
    <script src="~/admin/js/core/popper.min.js" type="text/javascript"></script>
    <script src="~/admin/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>
    <script src="~/admin/js/plugins/perfect-scrollbar.jquery.min.js"></script>
    <!--  Google Maps Plugin    -->
    <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
    <!-- Chartist JS -->
    <script src="~/admin/js/plugins/chartist.min.js"></script>
    <!--  Notifications Plugin    -->
    <script src="~/admin/js/plugins/bootstrap-notify.js"></script>
    <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="~/admin/js/material-dashboard.min.js?v=2.1.0" type="text/javascript"></script>
    <script>
        $('#@ViewData["ActivePage"]').addClass("active")
    </script>
</body>
</html>