ProjectFindStar/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjectFindStar.Data;
using ProjectFindStar.Services;

namespace ProjectFindStar.Areas.Admin.Controllers
{
    [Area(nameof(Admin))]
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly ILogger logger;
        public HomeController(ApplicationDbContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            this.ViewData["ActivePage"] = "index";
            return this.View();
        }

        public IActionResult Users()
        {
            this.ViewData["ActivePage"] = "users";
            DbSet<AppUser> users = this.context.Users;
            return this.View(users);
        }
    }
}

ProjectFindStar/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ProjectFindStar.Models;

namespace ProjectFindStar.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjectFindStar/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ProjectFindStar.Controllers
{
    public class MapController : Controller
    {
        public IActionResult Index()
        {
            ViewData["ShouldHideFooter"] = true;
            return View();
        }
    }
}

ProjectFindStar/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
    
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

ProjectFindStar/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ProjectFindStar/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="page-header clear-filter" filter-color="orange">
    <div class="page-header-image" style="background-image: url(/img/header.jpg);">
    </div>
    <div class="container">
        <div class="content-center brand">
            <img class="n-logo" src="~/img/logo-transparent.png" alt="">
            <h3>The best of Airbnb and Bing Maps combined into one universal and expansible app.</h3>
            <div class="row">
                <div class="col-md-4 ml-auto mr-auto">
                    <a asp-controller="Map" asp-action="Index" class="btn btn-primary btn-round btn-lg btn-block">Take me to the map</a>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    document.getElementsByTagName("body")[0].classList.add("index-page")
</script>